//------------------------------------------------------------------------------
// <auto-generated>

namespace Seventy.DomainClass.Core
{
    using Seventy.ViewModel;

    public partial class KmExperienceViewModel:CoreBaseViewModel
    {
        public int UserID { get; set; }
        public string Section { get; set; }
        public int CatID { get; set; }
        public int Priority { get; set; }
    }
}
